dataset: 'mnist2usps'
val_split: 0.2
image_size: [3, 32, 32]
batch_size: 32
num_epochs: 400
val_every: 1
optim:
  lr: 2.0e-4
  betas: [0.5, 0.999]
  clip_grad: 1.0
  sche_n_steps: [100, 100]
hparams:
  w_domain: [0.5, 0.5]
  cg_threshold: 0.9
  w_cg: !!float -1.0e3
  w_ent_reg: 1.0e-5
