model:
  in_shape: [3, 32, 32]
dataset:
  val_split: 0.2
  src:
    cls: MNIST
    kwargs: null
  tgt:
    cls: USPS
    kwargs: null
checkpoint: null
device: cuda
batch_size: 512
num_epochs: 100
val_every: 1
val_metric: -loss_G
n_vis: 50
oparams:
  lr: 2.0e-6
  betas: [0.5, 0.999]
hparams:
  cyc: 5
