model:
  in_shape: [3, 32, 32]
dataset:
  val_split: 0.2
  src:
    cls: MNIST
    kwargs: null
  tgt:
    cls: MNIST
    kwargs:
      tfs: {shrink: null}
checkpoint: null
device: cuda
batch_size: 128
num_epochs: 1000
val_every: 1
val_metric: -acc_t
oparams:
  lr: 2.0e-6
  betas: [0.5, 0.999]
hparams: {}
