model:
  in_shape: [3, 32, 32]
dataset:
  val_split: 0.2
  src:
    cls: MNIST
    kwargs: null
  tgt:
    cls: USPS
    kwargs: null
checkpoint: null
device: cuda
batch_size: 512
num_epochs: 200
val_every: 1
val_metric: -acc_t
n_vis: 50
oparams:
  lr: 2.0e-6
  betas: [0.9, 0.999]
hparams:
  dcls_ckpt: "C:\\Users\\xuanr\\Desktop\\Projects\\vdt2-pyro-3\\runs\\run1\\best_model.pth"
  beta_r: [1.0e-2, !!float 1.0e2]
