model:
  in_shape: [3, 32, 32]
dataset:
  val_split: 0.2
  src:
    cls: MNIST
    kwargs: null
  tgt:
    cls: USPS
    kwargs: null
checkpoint: null
device: cuda
batch_size: 32
num_epochs: 400
val_every: 1
val_metric: -acc_t
n_vis: 50
oparams:
  lr: 2.0e-4
  betas: [0.5, 0.999]
  clip_grad: 1.0
  sche_n_steps: [100, 100]
hparams:
  w_domain: [0.5, 0.5]
  # below fields are not used
  w_cg: !!float -1.0e3
  cg_threshold: 0.9
  w_er: !!float -1.0e3
  er_ratio: 1
  w_rer: !!float -1.0e3
  rer_ratio: 1
  w_rer_d: !!float -1.0e3
  rer_d_ratio: 0.5
