model:
  in_shape: [3, 32, 32]
dataset:
  val_split: 0.2
  src:
    cls: MNIST
    kwargs: null
  tgt:
    cls: MNIST
    kwargs:
      tfs: {colorize: null}
checkpoint: null
device: cuda
batch_size: 32
num_epochs: 400
val_every: 1
val_metric: -acc_t
n_vis: 50
oparams:
  lr: 2.0e-4
  betas: [0.9, 0.999]
hparams:
  w_domain: [0.5, 0.5]
  cg_threshold: 0.9
  w_cg: !!float -1.0e3
  w_ent_reg: 1.0e-5
